import type { Metadata } from "next";
import { Karantina, K2D } from "next/font/google";
import "./globals.css";

const karantina = Karantina({
  subsets: ["latin"],
  weight: "400"
});

const k2d = K2D({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-K2D"
})

export const metadata: Metadata = {
  title: "FisherCombustion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-white">
      <body className={`${karantina.className} ${k2d.variable}`}>{children}</body>
    </html>
  );
}
