import type { Metadata } from "next";
import { Jomhuria, Abel } from "next/font/google";
import "./globals.css";

const jomhuria = Jomhuria({
  subsets: ["latin"],
  weight: "400"
});

const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abel"
})

export const metadata: Metadata = {
  title: "FisherCombustion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="text-white">
      <body className={`${jomhuria.className} ${abel.variable}`}>{children}</body>
    </html>
  );
}
